name: reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: Ramesh-playground/tailspin-copy/.github/workflows/main.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:   
       - name: Download a Build Artifact
         uses: actions/download-artifact@v2.2.1
         with:
          name: spacegame
          path: C:\Users\rameshkumar\Desktop    
